services:
  db:
    image: mysql:8.1
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
  server:
    build: ./server
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./server:/rails
    ports:
      - "3002:3000"
    depends_on:
      - db
    environment:
      - SECRET_KEY_BASE
      - RAILS_ENV=production
      - MYSQL_ROOT_PASSWORD
    

volumes:
  db_data:
