name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to NAS using SSH
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.SECRET_KEY}}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{secrets.SSH_PORT}}
          script: |
            ssh 192.168.0.20
            cd ~/github/pam-quiz
            make production_deploy